2.Matrix operations (using vectorization) and transformation using python and SVD 
using Python.

Singular Value Decomposition

In [1]:
import numpy as np

In [2]:
from numpy.linalg import svd

In [3]:
A = np.array([[1,2,3], [4,5,6], [5,7,9]])

U, S, VT = svd(A)
print("Left Singular Vectors:")
print(U)
print("Singular Values:") 
print(np.diag(S))
print("Right Singular Vectors:") 
print(VT)

Left Singular Vectors:
[[-0.2354116   0.78182354 -0.57735027]
 [-0.55937325 -0.5947842  -0.57735027]
 [-0.79478485  0.18703934  0.57735027]]
Singular Values:
[[1.56633231e+01 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 8.12593979e-01 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 1.13716384e-15]]
Right Singular Vectors:
[[-0.41158755 -0.56381288 -0.71603821]
 [-0.8148184  -0.12429146  0.56623547]
 [-0.40824829  0.81649658 -0.40824829]]


In [4]:
print(U @ np.diag(S) @ VT)

[[1. 2. 3.]
 [4. 5. 6.]
 [5. 7. 9.]]


**SVD**


* Sklearn Truncated SVD - This is used for dimensional reduction directly




In [8]:
from sklearn.decomposition import TruncatedSVD
A = np.array([[1,2,3], [4,5,6], [5,7,9]])
print("Original Matrix:")
A

Original Matrix:


array([[1, 2, 3],
       [4, 5, 6],
       [5, 7, 9]])

In [9]:
svd =  TruncatedSVD(n_components = 2)  # reduce to 2 features
A_transf = svd.fit_transform(A)

print("Singular values:")
print(svd.singular_values_)
print()

Singular values:
[15.66332312  0.81259398]



In [10]:
print("Transformed Matrix after reducing to 2 features:")
print(A_transf)

Transformed Matrix after reducing to 2 features:
[[ 3.68732795  0.6353051 ]
 [ 8.76164389 -0.48331806]
 [12.44897184  0.15198704]]
