In [18]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [19]:
df=pd.read_csv('/content/Iris.csv')

In [20]:
df

Id  SepalLengthCm  ...  PetalWidthCm         Species
0      1            5.1  ...           0.2     Iris-setosa
1      2            4.9  ...           0.2     Iris-setosa
2      3            4.7  ...           0.2     Iris-setosa
3      4            4.6  ...           0.2     Iris-setosa
4      5            5.0  ...           0.2     Iris-setosa
..   ...            ...  ...           ...             ...
145  146            6.7  ...           2.3  Iris-virginica
146  147            6.3  ...           1.9  Iris-virginica
147  148            6.5  ...           2.0  Iris-virginica
148  149            6.2  ...           2.3  Iris-virginica
149  150            5.9  ...           1.8  Iris-virginica

[150 rows x 6 columns]

In [21]:
from sklearn.preprocessing import StandardScaler

In [22]:
scaler=StandardScaler()

In [24]:
scaler.fit(df.drop('Species',axis=1))

StandardScaler()

In [ ]:
StandardScaler()

StandardScaler()

In [25]:
scaled_feature=scaler.transform(df.drop('Species',axis=1))


In [26]:
new=pd.DataFrame(scaled_feature,columns=df.columns[:-1])
new

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0   -1.720542      -0.900681      1.032057      -1.341272     -1.312977
1   -1.697448      -1.143017     -0.124958      -1.341272     -1.312977
2   -1.674353      -1.385353      0.337848      -1.398138     -1.312977
3   -1.651258      -1.506521      0.106445      -1.284407     -1.312977
4   -1.628164      -1.021849      1.263460      -1.341272     -1.312977
..        ...            ...           ...            ...           ...
145  1.628164       1.038005     -0.124958       0.819624      1.447956
146  1.651258       0.553333     -1.281972       0.705893      0.922064
147  1.674353       0.795669     -0.124958       0.819624      1.053537
148  1.697448       0.432165      0.800654       0.933356      1.447956
149  1.720542       0.068662     -0.124958       0.762759      0.790591

[150 rows x 5 columns]

In [27]:
from sklearn.model_selection import train_test_split
x=new
y=df['Species']

In [28]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=42)


In [29]:
from sklearn.naive_bayes import GaussianNB,BernoulliNB,CategoricalNB
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

In [30]:
scores=[]
classifier=GaussianNB()
classifier.fit(x_train,y_train)
y_pred=classifier.predict(x_test)
scores.append(accuracy_score(y_test,y_pred))
cm=confusion_matrix(y_test,y_pred)
cm

array([[19,  0,  0],
       [ 0, 13,  0],
       [ 0,  0, 13]])

In [31]:
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))

[[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]
1.0
